#!/bin/sh

mkdir -p opk
cp ./vb.elf opk/vb.elf
cp ./vb.png opk/vb.png
cp ./COPYING opk/COPYING

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=VBEmu
Comment=Virtual Boy emulator
Exec=vb.elf %f
Icon=vb
Terminal=false
Type=Application
Categories=emulators;
X-OD-NeedsDownscaling=true
selectorbrowser=true
SelectorFilter=vb,VB,bin,BIN,rom,ROM
' > opk/default."$1".desktop

mksquashfs ./opk vbemu_"$1".opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
